name: Alt Arch Riscv64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build zoxide (riscv64)
    runs-on: ubuntu-24.04-riscv
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

      - name: Build
        run: |
          rustc --version
          time cargo build --release

      - name: Verify
        run: |
          ./target/release/zoxide --version
          file ./target/release/zoxide
